language: node_js

node_js:
  - "10"
cache:
  directories:
    - "node_modules"
install:
  - npm install
services:
  - postgresql

env:
  global:
  - NODE_ENV=test

before_script:
  - psql -c 'create database taskdbtest;' -U postgres
  - npm install -g sequelize-cli
  - npm install path
  - sequelize db:migrate
script:
  - npm test
after_success:
  - npm run coverage