version: 2
jobs:
    build:
        working_directory: ~/repo
        docker: 
            - image: circleci/node:10
            environment:
                PGHOST: 127.0.0.1
                PGUSER: postgres
                PGPASS: '12345678'
                NODE_ENV: testing
            - image: circleci/postgres:9.6.2-alpine
            environment:
                POSTGRES_DB: taskdbtest
                POSTGRES_PASSWORD: '12345678'
                POSTGRES_USER: postgres
        steps:
            - checkout
            - restore_cache:
                keys: 
                    - repo-yarn-{{ checksum "yarn.lock" }}
                    - repo-yarn-
            - run: yarn install
            - save_cache:
                paths:
                    - ~/.yarn-cache
                    key: repo-yarn-{{ checksum "yarn.lock" }}
            - run: dockerize -wait tcp://localhost:5432 -timeout 1m
            - run: yarn test validate.withCoverage
            - run: yarn test reportCoverage
            - store_artifacts:
                path: ./coverage/clover.xml
                prefix: tests
            - store_artifacts:
                path: coverage
                prefix: coverage
            - store_test_results:
                path: ./coverage/clover.xml 
